<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU4pi9ta\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU4pi9ta/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerU4pi9ta.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerU4pi9ta\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerU4pi9ta\appProdProjectContainer([
    'container.build_hash' => 'U4pi9ta',
    'container.build_id' => '39820651',
    'container.build_time' => 1634915941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU4pi9ta');
