<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ojqxxb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ojqxxb/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4ojqxxb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4ojqxxb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4ojqxxb\appProdProjectContainer([
    'container.build_hash' => '4ojqxxb',
    'container.build_id' => 'aacde518',
    'container.build_time' => 1634767607,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ojqxxb');
